import { describe, it, expect } from 'vitest';
import type { SupportReply } from './support-reply.js';
import {
    AI_DISCLAIMER,
    AI_DISCLAIMER_ESCALATED,
    AI_DISCLAIMER_REVIEWED,
    ResponseFormatter,
} from './formatter.js';

describe('disclaimer copy', () => {
    it('opens every variant with the plain AI-generated sentence', () => {
        expect(AI_DISCLAIMER).toBe('This is an AI-generated response.');
        expect(AI_DISCLAIMER_ESCALATED.startsWith(AI_DISCLAIMER)).toBe(true);
        expect(AI_DISCLAIMER_REVIEWED.startsWith(AI_DISCLAIMER)).toBe(true);
    });

    it('never volunteers a judgement about the response quality', () => {
        for (const text of [AI_DISCLAIMER, AI_DISCLAIMER_ESCALATED, AI_DISCLAIMER_REVIEWED]) {
            expect(text).not.toMatch(/incomplete|inaccurate|may not be|unreliable/i);
        }
    });

    it('only the escalated variant promises a follow-up in-thread', () => {
        expect(AI_DISCLAIMER_ESCALATED).toContain("We've escalated this to our engineering team");
        expect(AI_DISCLAIMER_REVIEWED).not.toContain('escalated');
    });
});

describe('ResponseFormatter', () => {
    const formatter = new ResponseFormatter();

    describe('Discord formatting', () => {
        it('should format response within 2000-char limit', () => {
            const result = formatter.format('Hello, here is your answer.', 'discord');

            expect(result.text).toContain('Hello, here is your answer.');
            expect(result.text).toContain('Powered by CopilotKit AI');
            expect(result.text.length).toBeLessThanOrEqual(2000);
            expect(result.truncated).toBe(false);
        });

        it('should include action buttons', () => {
            const result = formatter.format('Answer text', 'discord');

            expect(result.buttons).toBeDefined();
            expect(result.buttons).toHaveLength(3);
            expect(result.buttons![0].action).toBe('feedback_positive');
            expect(result.buttons![2].action).toBe('escalate');
        });

        it('should split long responses into multiple parts', () => {
            const longText = 'A'.repeat(2500);
            const result = formatter.format(longText, 'discord');

            expect(result.truncated).toBe(true);
            expect(result.parts).toBeDefined();
            expect(result.parts!.length).toBeGreaterThan(1);
            // Each part should be within limits
            for (const part of result.parts!) {
                expect(part.length).toBeLessThanOrEqual(2000);
            }
        });

        it('should handle code block splitting correctly', () => {
            // Create a message with a code block that forces a split
            const codeBlock = '```typescript\n' + 'const x = 1;\n'.repeat(150) + '```';
            const result = formatter.format(codeBlock, 'discord');

            if (result.parts && result.parts.length > 1) {
                // If split happened inside a code block, each part should have balanced fences
                for (const part of result.parts) {
                    const fenceCount = (part.match(/```/g) || []).length;
                    expect(fenceCount % 2).toBe(0);
                }
            }
        });

        it('should add disclaimer when requested', () => {
            const result = formatter.format('Answer text', 'discord', {
                addDisclaimer: true,
            });

            expect(result.text).toContain('AI-generated response');
        });

        it('never hedges about completeness on any platform', () => {
            for (const platform of ['discord', 'github', 'slack', 'teams', 'web'] as const) {
                const result = formatter.format('Answer text', platform, {
                    addDisclaimer: true,
                });
                expect(result.text).not.toMatch(/may be incomplete|might be incomplete/i);
                expect(result.text).toContain(AI_DISCLAIMER);
            }
        });

        it('should use custom disclaimer text', () => {
            const result = formatter.format('Answer text', 'discord', {
                addDisclaimer: true,
                disclaimerText: 'Low confidence response',
            });

            expect(result.text).toContain('Low confidence response');
        });
    });

    describe('GitHub formatting', () => {
        it('should include GitHub footer', () => {
            const result = formatter.format('Answer text', 'github');

            expect(result.text).toContain('Generated by CopilotKit AI Support');
            expect(result.text).toContain('Documentation');
            expect(result.truncated).toBe(false);
        });

        it('should wrap long code blocks in collapsible details', () => {
            const longCode = '```typescript\n' + 'const x = 1;\n'.repeat(50) + '```';
            const result = formatter.format(longCode, 'github');

            expect(result.text).toContain('<details>');
            expect(result.text).toContain('<summary>');
            expect(result.text).toContain('</details>');
        });

        it('should not wrap short code blocks in details', () => {
            const shortCode = '```typescript\nconst x = 1;\n```';
            const result = formatter.format(shortCode, 'github');

            expect(result.text).not.toContain('<details>');
        });
    });

    describe('Web formatting', () => {
        it('should include web footer', () => {
            const result = formatter.format('Answer text', 'web');

            expect(result.text).toContain('Powered by CopilotKit AI');
            expect(result.truncated).toBe(false);
        });

        it('should strip script tags', () => {
            const xss = 'Answer <script>alert("xss")</script> text';
            const result = formatter.format(xss, 'web');

            expect(result.text).not.toContain('<script>');
        });

        it('should strip iframe tags', () => {
            const xss = 'Answer <iframe src="evil.com"></iframe> text';
            const result = formatter.format(xss, 'web');

            expect(result.text).not.toContain('<iframe');
        });

        it('should strip event handlers', () => {
            const xss = 'Answer <div onclick="alert(1)">click me</div>';
            const result = formatter.format(xss, 'web');

            expect(result.text).not.toContain('onclick');
        });
    });
});

describe('structured support formatting', () => {
    const formatter = new ResponseFormatter();

    function reply(overrides: Partial<SupportReply> = {}): SupportReply {
        return {
            decision: 'answer',
            summary: 'Mount your chat inside the configured provider.',
            details: 'Configure the provider with your runtime URL.',
            apiVersion: 'v2',
            appliesTo: 'React applications',
            evidence: [
                {
                    sourceUrl: 'https://docs.copilotkit.ai/provider',
                    quote: 'Configure the provider with your runtime URL.',
                },
            ],
            handoffReason: '',
            ...overrides,
        };
    }

    it('starts GitHub with the useful summary and puts disclosure after one details section', () => {
        const result = formatter.formatStructured(reply(), 'github', {
            addDisclaimer: true,
            disclaimerText: AI_DISCLAIMER_ESCALATED,
        });
        expect(result.text.startsWith(reply().summary)).toBe(true);
        expect(result.text).toContain('<details><summary>Technical details and sources</summary>');
        expect(result.text.match(/<details>/g)).toHaveLength(1);
        expect(result.text.indexOf(AI_DISCLAIMER_ESCALATED)).toBeGreaterThan(
            result.text.indexOf('</details>'),
        );
        expect(result.text).toContain('Generated by CopilotKit AI Support');
    });

    it('keeps long code literal inside the single GitHub details wrapper', () => {
        const code = '```tsx\n' + '<Provider />\n'.repeat(50) + '```';
        const result = formatter.formatStructured(reply({ details: code }), 'github');
        expect(result.text).toContain(code);
        expect(result.text).not.toContain('&lt;Provider');
        expect(result.text.match(/<details>/g)).toHaveLength(1);
        expect(result.text).not.toContain('Code example');
    });

    it('returns web details separately while keeping the summary in the main text', () => {
        const result = formatter.formatStructured(reply(), 'web', { addDisclaimer: true });
        expect(result.text.startsWith(reply().summary)).toBe(true);
        expect(result.text).not.toContain(reply().details);
        expect(result.text).toContain('Powered by CopilotKit AI');
        expect(result.details).toContain(reply().details);
        expect(result.details).toContain('https://docs.copilotkit.ai/provider');
        expect(result.details).not.toContain('<details>');
    });

    it.each(['discord', 'slack', 'teams'] as const)(
        'uses ordinary platform formatting for %s',
        (platform) => {
            const result = formatter.formatStructured(reply(), platform);
            expect(result.text.startsWith(reply().summary)).toBe(true);
            expect(result.text).toContain(reply().details);
            expect(result.text).not.toContain('<details>');
            if (platform === 'discord') expect(result.buttons).toHaveLength(3);
        },
    );

    it.each(['discord', 'github', 'slack', 'teams', 'web'] as const)(
        'renders routes plainly on %s without draft details',
        (platform) => {
            const result = formatter.formatStructured(
                reply({ decision: 'route', handoffReason: 'Internal routing reason' }),
                platform,
            );
            expect(result.text.startsWith(reply().summary)).toBe(true);
            expect(result.text).not.toContain(reply().details);
            expect(result.text).not.toContain('Internal routing reason');
            expect(result.text).not.toContain('<details>');
            expect(result.details).toBeUndefined();
        },
    );
});
