import type { FormattedResponse } from './types.js';
import type { PlatformTarget } from '@copilotkit/outpost/shared';
import { supportReplyDetails, type SupportReply } from './support-reply.js';

const DISCORD_MAX_LENGTH = 2000;

/**
 * What a split costs when it lands inside a fenced code block: the fence is closed
 * on the part being emitted and reopened on the next one. Both are appended after
 * the split point is chosen, so both are charged against the budget rather than
 * assumed to fit.
 */
const FENCE_CLOSE = '\n```';
const FENCE_REOPEN = '```\n';

const STANDARD_FOOTER =
    '\n\n---\n*Powered by CopilotKit AI · [Docs](https://docs.copilotkit.ai) · Was this helpful? React with 👍 or 👎*';

const GITHUB_FOOTER =
    '\n\n---\n<sub>🤖 Generated by CopilotKit AI Support · [Documentation](https://docs.copilotkit.ai)</sub>';

const WEB_FOOTER = '\n\n---\n*Powered by CopilotKit AI*';

/**
 * The disclaimer sentence every externally-visible AI response opens with.
 *
 * Deliberately narrow: it states WHAT wrote the response, never volunteers a
 * judgement about the response's quality. Copy like "and may be incomplete"
 * must never ship to a public GitHub issue or Discord thread — it invites the
 * reader to distrust an answer we chose to post. Confidence is handled by the
 * pipeline (a low-confidence answer escalates or isn't sent), not by hedging in
 * front of the user.
 */
export const AI_DISCLAIMER = 'This is an AI-generated response.';

/** Disclaimer for responses the worker will actually enqueue an escalation for. */
export const AI_DISCLAIMER_ESCALATED = `${AI_DISCLAIMER} We've escalated this to our engineering team — someone will follow up in this thread shortly.`;

/** Disclaimer for responses that post without a guaranteed human follow-up. */
export const AI_DISCLAIMER_REVIEWED = `${AI_DISCLAIMER} A member of our team will review and follow up if needed.`;

/**
 * The whole formatted response as one string, for a sink that holds exactly one:
 * the durable `suggestedResponse`, the shadow record, the string stream.
 *
 * Reads {@link FormattedResponse.completeText} when the formatter composed one —
 * the web split is the only case, and it is the only correct serialization of it,
 * because `text` there is just the summary pane and already carries the closing
 * footer. Otherwise `text` (or `parts`, which supersede it: a split format repeats
 * its first part in `text`, so publishing both would duplicate it) is already the
 * whole response.
 *
 * The trailing `details` join is the compatibility path, not the intended one. It
 * reproduces, byte for byte, how a `FormattedResponse` serialized before
 * `completeText` existed, so a hand-built value or one read back from an older run
 * is unchanged by this function's introduction. A formatter result always takes
 * the `completeText` branch instead.
 */
export function publishableText(formatted: FormattedResponse): string {
    if (formatted.completeText) return formatted.completeText;
    const body = formatted.parts?.length ? formatted.parts.join('\n\n') : formatted.text;
    return [body, formatted.details].filter(Boolean).join('\n\n');
}

/**
 * True when `index` holds the leading half of a surrogate pair completed at
 * `index + 1` — that is, when a cut between the two would leave both halves
 * unpaired.
 */
function splitsSurrogatePair(text: string, index: number): boolean {
    const leading = text.charCodeAt(index);
    const trailing = text.charCodeAt(index + 1);
    return leading >= 0xd800 && leading <= 0xdbff && trailing >= 0xdc00 && trailing <= 0xdfff;
}

/**
 * Formats AI-generated responses for different platform targets.
 *
 * - Discord: markdown with 2000-char limit, splits into multiple messages, adds action buttons
 * - GitHub: full markdown with collapsible details sections
 * - Web: HTML-safe markdown
 */
export class ResponseFormatter {
    /** Render a validated reply with its useful summary first on every platform. */
    formatStructured(
        reply: SupportReply,
        platform: PlatformTarget,
        options?: { addDisclaimer?: boolean; disclaimerText?: string },
    ): FormattedResponse {
        const details = supportReplyDetails(reply);
        const disclaimer = options?.addDisclaimer
            ? `\n\n> ${options.disclaimerText ?? AI_DISCLAIMER_REVIEWED}`
            : '';

        if (platform === 'github') {
            const expanded = details
                ? `\n\n<details><summary>Technical details and sources</summary>\n\n${details}\n\n</details>`
                : '';
            return {
                text: reply.summary + expanded + disclaimer + GITHUB_FOOTER,
                truncated: false,
            };
        }
        if (platform === 'web') {
            // Both panes of the web split are spliced from a VALIDATED reply, so both
            // carry their fields as written. `validateSupportReply` runs the same
            // prose check over `summary`, `details` and `appliesTo`: raw HTML outside
            // code is refused outright, and a tag inside a fence or a code span is
            // deliberately published, because the chat surface renders Markdown
            // through ReactMarkdown with no rehype-raw and it reaches the reader as
            // the inert literal the answer meant. Anything the web sanitizer could
            // still find in these fields is therefore an answer's own example, and
            // deleting it is how `Use \`<button onclick="handleClick()">Run</button>\``
            // reached a reader as `<button >Run</button>` — a wrong answer, not a
            // safe one. The defence belongs on an unvalidated body, which is what
            // `formatWeb` still guards on the legacy `format()` path.
            //
            // The disclaimer is the one piece here that nothing validated — it is
            // whatever the caller passed — so it keeps the sanitizer. Both panes
            // close with the same `trailing` expression, which is what makes the
            // disclaimer land once and the footer last in each of them.
            const trailing = this.sanitizeWeb(disclaimer) + WEB_FOOTER;
            const summaryPane: FormattedResponse = {
                text: reply.summary + trailing,
                truncated: false,
            };
            if (!details) return summaryPane;
            return {
                ...summaryPane,
                details,
                // The same pieces in reading order, closed by one footer, for the
                // sinks that hold a single string. Composed here rather than by
                // appending `details` to `summaryPane.text`, which would leave the
                // footer stranded between the summary and the details.
                completeText: [reply.summary, details].join('\n\n') + trailing,
            };
        }

        const text = [reply.summary, details].filter(Boolean).join('\n\n') + disclaimer;
        return platform === 'discord' ? this.formatDiscord(text) : this.formatWeb(text);
    }

    /**
     * Format a response for the specified platform.
     */
    format(
        text: string,
        platform: PlatformTarget,
        options?: { addDisclaimer?: boolean; disclaimerText?: string },
    ): FormattedResponse {
        const disclaimer = options?.addDisclaimer
            ? `> ⚠️ ${options.disclaimerText ?? AI_DISCLAIMER_REVIEWED}\n\n`
            : '';

        const fullText = disclaimer + text;

        switch (platform) {
            case 'discord':
                return this.formatDiscord(fullText);
            case 'github':
                return this.formatGitHub(fullText);
            case 'slack':
            case 'teams':
            case 'web':
                return this.formatWeb(fullText);
        }
    }

    private formatDiscord(text: string): FormattedResponse {
        const withFooter = text + STANDARD_FOOTER;

        // Discord buttons metadata for the bot to attach
        const buttons = [
            { label: '👍 Helpful', action: 'feedback_positive' },
            { label: '👎 Not Helpful', action: 'feedback_negative' },
            { label: '🧑‍💻 Talk to Human', action: 'escalate' },
        ];

        if (withFooter.length <= DISCORD_MAX_LENGTH) {
            return {
                text: withFooter,
                buttons,
                truncated: false,
            };
        }

        // Split into multiple parts, preserving code blocks. The splitter is told how
        // much the footer will cost so the last part comes back with room for it; there
        // is therefore nothing left to cut here, and nothing may be cut — the end of the
        // last message is the footer, so trimming to fit removes the Docs link and the
        // 👍/👎 prompt from a response a user reads, and can leave half a surrogate pair
        // where an emoji was.
        const parts = this.splitForDiscord(text, STANDARD_FOOTER.length);
        parts[parts.length - 1] += STANDARD_FOOTER;

        return {
            text: parts[0],
            parts,
            buttons,
            truncated: true,
        };
    }

    /**
     * Split `text` into messages that each fit Discord's cap, leaving the LAST one
     * `footerLength` characters free for the footer the caller appends to it.
     *
     * The budget is the whole job. Everything appended after the split point is
     * chosen has to be counted here, because Discord rejects an oversized message and
     * the only way to recover downstream is to cut copy that was meant to be read.
     * Two things are appended: the footer, on the last part, and the fence this
     * function closes on a part when the split lands inside a code block. A reserve
     * that under-counts either one is not a smaller margin — it is a message that
     * cannot be posted as composed.
     */
    private splitForDiscord(text: string, footerLength: number): string[] {
        const parts: string[] = [];
        // Charged on every part, because any part may be the one a fence is closed on.
        const maxPartLength = DISCORD_MAX_LENGTH - FENCE_CLOSE.length;

        let remaining = text;
        while (remaining.length > 0) {
            if (remaining.length + footerLength <= DISCORD_MAX_LENGTH) {
                parts.push(remaining);
                break;
            }

            // Cutting as late as the budget allows would answer a body that overruns by
            // a few characters with a continuation message that is almost entirely
            // footer, so the cut also leaves at least the footer's own length behind.
            // The floor of 1 is for termination only: it cannot be reached while the
            // footer is shorter than the cap.
            const limit = Math.max(1, Math.min(maxPartLength, remaining.length - footerLength));
            const { splitAt, separatorLength } = this.splitPoint(remaining, limit);

            const part = remaining.slice(0, splitAt);
            const insideCodeBlock = (part.match(/```/g) ?? []).length % 2 !== 0;
            parts.push(insideCodeBlock ? part + FENCE_CLOSE : part);
            remaining =
                (insideCodeBlock ? FENCE_REOPEN : '') + remaining.slice(splitAt + separatorLength);
        }

        return parts;
    }

    /**
     * Where to break `text` at or before `limit`, and how many characters of it the
     * break consumes.
     *
     * Breaking on whitespace consumes exactly the whitespace it broke on and not a
     * character more. What follows a newline is the next line's indentation, which
     * inside a fenced block is the snippet's own structure — absorbing it silently
     * rewrites code the reader is being told to copy.
     */
    private splitPoint(text: string, limit: number): { splitAt: number; separatorLength: number } {
        // Prefer paragraph breaks, then newlines, then spaces — but only in the back
        // half of the budget, so a body with one early break still fills its messages.
        const earliestUsefulBreak = limit * 0.5;

        const paragraphBreak = text.lastIndexOf('\n\n', limit);
        if (paragraphBreak > earliestUsefulBreak) {
            return { splitAt: paragraphBreak, separatorLength: 2 };
        }

        const lineBreak = text.lastIndexOf('\n', limit);
        if (lineBreak > earliestUsefulBreak) {
            return { splitAt: lineBreak, separatorLength: 1 };
        }

        const space = text.lastIndexOf(' ', limit);
        if (space > earliestUsefulBreak) {
            return { splitAt: space, separatorLength: 1 };
        }

        // Nothing to break on, so cut at the limit — but never between the two code
        // units of an astral character such as 👍. That is not a rendering nit: it
        // produces an unpaired surrogate, an ill-formed string, in published copy.
        const cutsAnAstralCharacter = limit > 1 && splitsSurrogatePair(text, limit - 1);
        return { splitAt: cutsAnAstralCharacter ? limit - 1 : limit, separatorLength: 0 };
    }

    private formatGitHub(text: string): FormattedResponse {
        // Wrap long code blocks in collapsible details
        const formatted = text.replace(/```(\w+)?\n([\s\S]{500,}?)```/g, (match, lang, code) => {
            const langLabel = lang ? ` (${lang})` : '';
            return `<details><summary>Code example${langLabel}</summary>\n\n\`\`\`${lang ?? ''}\n${code}\`\`\`\n</details>`;
        });

        return {
            text: formatted + GITHUB_FOOTER,
            truncated: false,
        };
    }

    /**
     * Strip the raw HTML an UNVALIDATED body could be carrying as markup.
     *
     * This is `formatWeb`'s defence, and it is a blunt one: it deletes a `<script>`
     * or `<iframe>` element whole and drops every `on*` attribute, with no notion of
     * whether what it found was markup or an example. That is the right trade for a
     * free-text body nothing else has checked, which is what the legacy `format()`
     * path hands it.
     *
     * It is the wrong trade for a validated reply's own fields, which have already
     * been held to a stricter rule by a real parser. That is why the `web` branch of
     * `formatStructured` runs it over the caller-supplied disclaimer only — see the
     * web composition for what the difference costs a reader.
     *
     * That narrowing is the `web` branch's alone. `formatStructured` still falls
     * through to the legacy `formatWeb` for `slack` and `teams`, so on those two
     * platforms the whole composed body — validated summary and details included —
     * is sanitized, and a validated answer carrying a `<script>`/`<iframe>` element
     * or an `on*` attribute pays there exactly the cost the web composition
     * describes. Routing them off `formatWeb` is a tracked follow-up, not something
     * this docblock should be read as claiming already happened.
     */
    private sanitizeWeb(text: string): string {
        return text
            .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
            .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, '')
            .replace(/on\w+="[^"]*"/gi, '');
    }

    private formatWeb(text: string): FormattedResponse {
        return {
            text: this.sanitizeWeb(text) + WEB_FOOTER,
            truncated: false,
        };
    }
}
