import type { FormattedResponse } from './types.js';
import type { PlatformTarget } from '@copilotkit/outpost/shared';
import { supportReplyDetails, type SupportReply } from './support-reply.js';

const DISCORD_MAX_LENGTH = 2000;

const STANDARD_FOOTER =
    '\n\n---\n*Powered by CopilotKit AI · [Docs](https://docs.copilotkit.ai) · Was this helpful? React with 👍 or 👎*';

const GITHUB_FOOTER =
    '\n\n---\n<sub>🤖 Generated by CopilotKit AI Support · [Documentation](https://docs.copilotkit.ai)</sub>';

const WEB_FOOTER = '\n\n---\n*Powered by CopilotKit AI*';

/**
 * The disclaimer sentence every externally-visible AI response opens with.
 *
 * Deliberately narrow: it states WHAT wrote the response, never volunteers a
 * judgement about the response's quality. Copy like "and may be incomplete"
 * must never ship to a public GitHub issue or Discord thread — it invites the
 * reader to distrust an answer we chose to post. Confidence is handled by the
 * pipeline (a low-confidence answer escalates or isn't sent), not by hedging in
 * front of the user.
 */
export const AI_DISCLAIMER = 'This is an AI-generated response.';

/** Disclaimer for responses the worker will actually enqueue an escalation for. */
export const AI_DISCLAIMER_ESCALATED = `${AI_DISCLAIMER} We've escalated this to our engineering team — someone will follow up in this thread shortly.`;

/** Disclaimer for responses that post without a guaranteed human follow-up. */
export const AI_DISCLAIMER_REVIEWED = `${AI_DISCLAIMER} A member of our team will review and follow up if needed.`;

/**
 * The whole formatted response as one string, for a sink that holds exactly one:
 * the durable `suggestedResponse`, the shadow record, the string stream.
 *
 * Reads {@link FormattedResponse.completeText} when the formatter composed one —
 * the web split is the only case, and it is the only correct serialization of it,
 * because `text` there is just the summary pane and already carries the closing
 * footer. Otherwise `text` (or `parts`, which supersede it: a split format repeats
 * its first part in `text`, so publishing both would duplicate it) is already the
 * whole response.
 *
 * The trailing `details` join is the compatibility path, not the intended one. It
 * reproduces, byte for byte, how a `FormattedResponse` serialized before
 * `completeText` existed, so a hand-built value or one read back from an older run
 * is unchanged by this function's introduction. A formatter result always takes
 * the `completeText` branch instead.
 */
export function publishableText(formatted: FormattedResponse): string {
    if (formatted.completeText) return formatted.completeText;
    const body = formatted.parts?.length ? formatted.parts.join('\n\n') : formatted.text;
    return [body, formatted.details].filter(Boolean).join('\n\n');
}

/**
 * Formats AI-generated responses for different platform targets.
 *
 * - Discord: markdown with 2000-char limit, splits into multiple messages, adds action buttons
 * - GitHub: full markdown with collapsible details sections
 * - Web: HTML-safe markdown
 */
export class ResponseFormatter {
    /** Render a validated reply with its useful summary first on every platform. */
    formatStructured(
        reply: SupportReply,
        platform: PlatformTarget,
        options?: { addDisclaimer?: boolean; disclaimerText?: string },
    ): FormattedResponse {
        const details = supportReplyDetails(reply);
        const disclaimer = options?.addDisclaimer
            ? `\n\n> ${options.disclaimerText ?? AI_DISCLAIMER_REVIEWED}`
            : '';

        if (platform === 'github') {
            const expanded = details
                ? `\n\n<details><summary>Technical details and sources</summary>\n\n${details}\n\n</details>`
                : '';
            return {
                text: reply.summary + expanded + disclaimer + GITHUB_FOOTER,
                truncated: false,
            };
        }
        if (platform === 'web') {
            const summaryPane = this.formatWeb(reply.summary + disclaimer);
            if (!details) return summaryPane;
            return {
                ...summaryPane,
                details,
                // The same pieces in reading order, closed by one footer, for the
                // sinks that hold a single string. Composed here rather than by
                // appending `details` to `summaryPane.text`, which would leave the
                // footer stranded between the summary and the details.
                completeText: this.formatWeb([reply.summary, details].join('\n\n') + disclaimer)
                    .text,
            };
        }

        const text = [reply.summary, details].filter(Boolean).join('\n\n') + disclaimer;
        return platform === 'discord' ? this.formatDiscord(text) : this.formatWeb(text);
    }

    /**
     * Format a response for the specified platform.
     */
    format(
        text: string,
        platform: PlatformTarget,
        options?: { addDisclaimer?: boolean; disclaimerText?: string },
    ): FormattedResponse {
        const disclaimer = options?.addDisclaimer
            ? `> ⚠️ ${options.disclaimerText ?? AI_DISCLAIMER_REVIEWED}\n\n`
            : '';

        const fullText = disclaimer + text;

        switch (platform) {
            case 'discord':
                return this.formatDiscord(fullText);
            case 'github':
                return this.formatGitHub(fullText);
            case 'slack':
            case 'teams':
            case 'web':
                return this.formatWeb(fullText);
        }
    }

    private formatDiscord(text: string): FormattedResponse {
        const withFooter = text + STANDARD_FOOTER;

        // Discord buttons metadata for the bot to attach
        const buttons = [
            { label: '👍 Helpful', action: 'feedback_positive' },
            { label: '👎 Not Helpful', action: 'feedback_negative' },
            { label: '🧑‍💻 Talk to Human', action: 'escalate' },
        ];

        if (withFooter.length <= DISCORD_MAX_LENGTH) {
            return {
                text: withFooter,
                buttons,
                truncated: false,
            };
        }

        // Split into multiple parts, preserving code blocks
        const parts = this.splitForDiscord(text);

        // Add footer only to the last part
        const lastIdx = parts.length - 1;
        parts[lastIdx] = parts[lastIdx] + STANDARD_FOOTER;

        // If even the last part is too long after footer, truncate it
        if (parts[lastIdx].length > DISCORD_MAX_LENGTH) {
            parts[lastIdx] = parts[lastIdx].slice(0, DISCORD_MAX_LENGTH - 3) + '...';
        }

        return {
            text: parts[0],
            parts,
            buttons,
            truncated: true,
        };
    }

    private splitForDiscord(text: string): string[] {
        const parts: string[] = [];
        // Reserve space for potential "... (continued)" markers
        const maxPartLength = DISCORD_MAX_LENGTH - 50;

        let remaining = text;
        while (remaining.length > 0) {
            if (remaining.length <= maxPartLength) {
                parts.push(remaining);
                break;
            }

            // Find a good split point: prefer paragraph breaks, then newlines, then spaces
            let splitAt = maxPartLength;

            const paragraphBreak = remaining.lastIndexOf('\n\n', maxPartLength);
            if (paragraphBreak > maxPartLength * 0.5) {
                splitAt = paragraphBreak;
            } else {
                const lineBreak = remaining.lastIndexOf('\n', maxPartLength);
                if (lineBreak > maxPartLength * 0.5) {
                    splitAt = lineBreak;
                } else {
                    const space = remaining.lastIndexOf(' ', maxPartLength);
                    if (space > maxPartLength * 0.5) {
                        splitAt = space;
                    }
                }
            }

            // Check if we're splitting inside a code block
            const part = remaining.slice(0, splitAt);
            const openFences = (part.match(/```/g) || []).length;
            if (openFences % 2 !== 0) {
                // We're inside a code block — close it and reopen in next part
                parts.push(part + '\n```');
                remaining = '```\n' + remaining.slice(splitAt).trimStart();
            } else {
                parts.push(part);
                remaining = remaining.slice(splitAt).trimStart();
            }
        }

        return parts;
    }

    private formatGitHub(text: string): FormattedResponse {
        // Wrap long code blocks in collapsible details
        const formatted = text.replace(/```(\w+)?\n([\s\S]{500,}?)```/g, (match, lang, code) => {
            const langLabel = lang ? ` (${lang})` : '';
            return `<details><summary>Code example${langLabel}</summary>\n\n\`\`\`${lang ?? ''}\n${code}\`\`\`\n</details>`;
        });

        return {
            text: formatted + GITHUB_FOOTER,
            truncated: false,
        };
    }

    private formatWeb(text: string): FormattedResponse {
        // For web, ensure markdown is clean and HTML-safe
        // Escape any raw HTML that isn't part of markdown
        const sanitized = text
            .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
            .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, '')
            .replace(/on\w+="[^"]*"/gi, '');

        return {
            text: sanitized + WEB_FOOTER,
            truncated: false,
        };
    }
}
