import { describe, it, expect } from 'vitest';
import type { SupportReply } from './support-reply.js';
import {
    AI_DISCLAIMER,
    AI_DISCLAIMER_ESCALATED,
    AI_DISCLAIMER_REVIEWED,
    ResponseFormatter,
    publishableText,
} from './formatter.js';

describe('disclaimer copy', () => {
    it('opens every variant with the plain AI-generated sentence', () => {
        expect(AI_DISCLAIMER).toBe('This is an AI-generated response.');
        expect(AI_DISCLAIMER_ESCALATED.startsWith(AI_DISCLAIMER)).toBe(true);
        expect(AI_DISCLAIMER_REVIEWED.startsWith(AI_DISCLAIMER)).toBe(true);
    });

    it('never volunteers a judgement about the response quality', () => {
        for (const text of [AI_DISCLAIMER, AI_DISCLAIMER_ESCALATED, AI_DISCLAIMER_REVIEWED]) {
            expect(text).not.toMatch(/incomplete|inaccurate|may not be|unreliable/i);
        }
    });

    it('only the escalated variant promises a follow-up in-thread', () => {
        expect(AI_DISCLAIMER_ESCALATED).toContain("We've escalated this to our engineering team");
        expect(AI_DISCLAIMER_REVIEWED).not.toContain('escalated');
    });
});

describe('ResponseFormatter', () => {
    const formatter = new ResponseFormatter();

    describe('Discord formatting', () => {
        it('should format response within 2000-char limit', () => {
            const result = formatter.format('Hello, here is your answer.', 'discord');

            expect(result.text).toContain('Hello, here is your answer.');
            expect(result.text).toContain('Powered by CopilotKit AI');
            expect(result.text.length).toBeLessThanOrEqual(2000);
            expect(result.truncated).toBe(false);
        });

        it('should include action buttons', () => {
            const result = formatter.format('Answer text', 'discord');

            expect(result.buttons).toBeDefined();
            expect(result.buttons).toHaveLength(3);
            expect(result.buttons![0].action).toBe('feedback_positive');
            expect(result.buttons![2].action).toBe('escalate');
        });

        it('should split long responses into multiple parts', () => {
            const longText = 'A'.repeat(2500);
            const result = formatter.format(longText, 'discord');

            expect(result.truncated).toBe(true);
            expect(result.parts).toBeDefined();
            expect(result.parts!.length).toBeGreaterThan(1);
            // Each part should be within limits
            for (const part of result.parts!) {
                expect(part.length).toBeLessThanOrEqual(2000);
            }
        });

        it('should handle code block splitting correctly', () => {
            // Create a message with a code block that forces a split
            const codeBlock = '```typescript\n' + 'const x = 1;\n'.repeat(150) + '```';
            const result = formatter.format(codeBlock, 'discord');

            if (result.parts && result.parts.length > 1) {
                // If split happened inside a code block, each part should have balanced fences
                for (const part of result.parts) {
                    const fenceCount = (part.match(/```/g) || []).length;
                    expect(fenceCount % 2).toBe(0);
                }
            }
        });

        it('should add disclaimer when requested', () => {
            const result = formatter.format('Answer text', 'discord', {
                addDisclaimer: true,
            });

            expect(result.text).toContain('AI-generated response');
        });

        it('never hedges about completeness on any platform', () => {
            for (const platform of ['discord', 'github', 'slack', 'teams', 'web'] as const) {
                const result = formatter.format('Answer text', platform, {
                    addDisclaimer: true,
                });
                expect(result.text).not.toMatch(/may be incomplete|might be incomplete/i);
                expect(result.text).toContain(AI_DISCLAIMER);
            }
        });

        it('should use custom disclaimer text', () => {
            const result = formatter.format('Answer text', 'discord', {
                addDisclaimer: true,
                disclaimerText: 'Low confidence response',
            });

            expect(result.text).toContain('Low confidence response');
        });
    });

    describe('GitHub formatting', () => {
        it('should include GitHub footer', () => {
            const result = formatter.format('Answer text', 'github');

            expect(result.text).toContain('Generated by CopilotKit AI Support');
            expect(result.text).toContain('Documentation');
            expect(result.truncated).toBe(false);
        });

        it('should wrap long code blocks in collapsible details', () => {
            const longCode = '```typescript\n' + 'const x = 1;\n'.repeat(50) + '```';
            const result = formatter.format(longCode, 'github');

            expect(result.text).toContain('<details>');
            expect(result.text).toContain('<summary>');
            expect(result.text).toContain('</details>');
        });

        it('should not wrap short code blocks in details', () => {
            const shortCode = '```typescript\nconst x = 1;\n```';
            const result = formatter.format(shortCode, 'github');

            expect(result.text).not.toContain('<details>');
        });
    });

    describe('Web formatting', () => {
        it('should include web footer', () => {
            const result = formatter.format('Answer text', 'web');

            expect(result.text).toContain('Powered by CopilotKit AI');
            expect(result.truncated).toBe(false);
        });

        it('should strip script tags', () => {
            const xss = 'Answer <script>alert("xss")</script> text';
            const result = formatter.format(xss, 'web');

            expect(result.text).not.toContain('<script>');
        });

        it('should strip iframe tags', () => {
            const xss = 'Answer <iframe src="evil.com"></iframe> text';
            const result = formatter.format(xss, 'web');

            expect(result.text).not.toContain('<iframe');
        });

        it('should strip event handlers', () => {
            const xss = 'Answer <div onclick="alert(1)">click me</div>';
            const result = formatter.format(xss, 'web');

            expect(result.text).not.toContain('onclick');
        });
    });
});

describe('structured support formatting', () => {
    const formatter = new ResponseFormatter();

    function reply(overrides: Partial<SupportReply> = {}): SupportReply {
        return {
            decision: 'answer',
            summary: 'Mount your chat inside the configured provider.',
            details: 'Configure the provider with your runtime URL.',
            apiVersion: 'v2',
            appliesTo: 'React applications',
            evidence: [
                {
                    sourceUrl: 'https://docs.copilotkit.ai/provider',
                    quote: 'Configure the provider with your runtime URL.',
                },
            ],
            handoffReason: '',
            ...overrides,
        };
    }

    it('starts GitHub with the useful summary and puts disclosure after one details section', () => {
        const result = formatter.formatStructured(reply(), 'github', {
            addDisclaimer: true,
            disclaimerText: AI_DISCLAIMER_ESCALATED,
        });
        expect(result.text.startsWith(reply().summary)).toBe(true);
        expect(result.text).toContain('<details><summary>Technical details and sources</summary>');
        expect(result.text.match(/<details>/g)).toHaveLength(1);
        expect(result.text.indexOf(AI_DISCLAIMER_ESCALATED)).toBeGreaterThan(
            result.text.indexOf('</details>'),
        );
        expect(result.text).toContain('Generated by CopilotKit AI Support');
    });

    it('keeps long code literal inside the single GitHub details wrapper', () => {
        const code = '```tsx\n' + '<Provider />\n'.repeat(50) + '```';
        const result = formatter.formatStructured(reply({ details: code }), 'github');
        expect(result.text).toContain(code);
        expect(result.text).not.toContain('&lt;Provider');
        expect(result.text.match(/<details>/g)).toHaveLength(1);
        expect(result.text).not.toContain('Code example');
    });

    it('returns web details separately while keeping the summary in the main text', () => {
        const result = formatter.formatStructured(reply(), 'web', { addDisclaimer: true });
        expect(result.text.startsWith(reply().summary)).toBe(true);
        expect(result.text).not.toContain(reply().details);
        expect(result.text).toContain('Powered by CopilotKit AI');
        expect(result.details).toContain(reply().details);
        expect(result.details).toContain('https://docs.copilotkit.ai/provider');
        expect(result.details).not.toContain('<details>');
    });

    it.each(['discord', 'slack', 'teams'] as const)(
        'uses ordinary platform formatting for %s',
        (platform) => {
            const result = formatter.formatStructured(reply(), platform);
            expect(result.text.startsWith(reply().summary)).toBe(true);
            expect(result.text).toContain(reply().details);
            expect(result.text).not.toContain('<details>');
            if (platform === 'discord') expect(result.buttons).toHaveLength(3);
        },
    );

    // The composed details are the last transform between a validated reply and the
    // reader, and the source list is the one part of them this formatter's caller
    // appends rather than the model writing it. Every destination it introduces has
    // to be an evidence URL, and where there is no evidence it introduces none.
    it('appends a source list holding only evidence destinations', () => {
        const value = reply({
            evidence: [
                { sourceUrl: 'https://docs.copilotkit.ai/provider', quote: 'Configure it.' },
                { sourceUrl: 'https://docs.copilotkit.ai/runtime', quote: 'Mount it.' },
            ],
        });
        const details = formatter.formatStructured(value, 'web').details ?? '';

        expect([...details.matchAll(/]\(<([^>]*)>\)/g)].map((match) => match[1])).toEqual(
            value.evidence.map((evidence) => evidence.sourceUrl),
        );
        expect(details).not.toMatch(/https?:\/\/(?!docs\.copilotkit\.ai\/(provider|runtime)\b)/);
    });

    it('appends no destination at all to a reply carrying no evidence', () => {
        const details = formatter.formatStructured(reply({ evidence: [] }), 'web').details ?? '';

        expect(details).not.toContain('**Sources**');
        expect(details).not.toMatch(/https?:\/\//);
    });

    it.each(['discord', 'github', 'slack', 'teams', 'web'] as const)(
        'renders routes plainly on %s without draft details',
        (platform) => {
            const result = formatter.formatStructured(
                reply({ decision: 'route', handoffReason: 'Internal routing reason' }),
                platform,
            );
            expect(result.text.startsWith(reply().summary)).toBe(true);
            expect(result.text).not.toContain(reply().details);
            expect(result.text).not.toContain('Internal routing reason');
            expect(result.text).not.toContain('<details>');
            expect(result.details).toBeUndefined();
            expect(result.completeText).toBeUndefined();
        },
    );

    // The web split is a UI contract, not a serialization: `text` and `details`
    // are two panes of one disclosure, and `text` already carries the footer that
    // closes the whole response. A sink that can only hold one string therefore
    // cannot be served by concatenating them — that buries the footer and the
    // disclaimer mid-response. `completeText` is the formatter answering that
    // question itself, since it is the only place that knows where the footer goes.
    describe('web completeText', () => {
        it('closes the single-string serialization with the footer, after the details', () => {
            const result = formatter.formatStructured(reply(), 'web', {
                addDisclaimer: true,
                disclaimerText: AI_DISCLAIMER_ESCALATED,
            });
            const complete = result.completeText ?? '';

            expect(complete.startsWith(reply().summary)).toBe(true);
            expect(complete.endsWith('\n\n---\n*Powered by CopilotKit AI*')).toBe(true);
            expect(complete.indexOf(reply().details)).toBeGreaterThan(
                complete.indexOf(reply().summary),
            );
            expect(complete.indexOf(AI_DISCLAIMER_ESCALATED)).toBeGreaterThan(
                complete.indexOf(reply().details),
            );
            expect(complete.indexOf('*Powered by CopilotKit AI*')).toBeGreaterThan(
                complete.indexOf(AI_DISCLAIMER_ESCALATED),
            );
        });

        it('carries the footer, disclaimer, summary and details exactly once each', () => {
            const result = formatter.formatStructured(reply(), 'web', {
                addDisclaimer: true,
                disclaimerText: AI_DISCLAIMER_REVIEWED,
            });
            const complete = result.completeText ?? '';

            for (const once of [
                reply().summary,
                reply().details,
                AI_DISCLAIMER_REVIEWED,
                '*Powered by CopilotKit AI*',
                'https://docs.copilotkit.ai/provider',
            ]) {
                expect(complete.split(once)).toHaveLength(2);
            }
        });

        it('leaves the two-pane text/details UI contract untouched', () => {
            const result = formatter.formatStructured(reply(), 'web', { addDisclaimer: true });

            expect(result.text.startsWith(reply().summary)).toBe(true);
            expect(result.text).not.toContain(reply().details);
            expect(result.text.endsWith('\n\n---\n*Powered by CopilotKit AI*')).toBe(true);
            expect(result.details).toContain(reply().details);
            expect(result.details).not.toContain('*Powered by CopilotKit AI*');
        });
    });

    // Every platform whose `text` is already the whole response must stay byte-identical;
    // a second serialization is exactly the duplicate-footer bug in the other direction.
    it.each(['discord', 'github', 'slack', 'teams'] as const)(
        'leaves %s with no second serialization to disagree with its text',
        (platform) => {
            expect(formatter.formatStructured(reply(), platform).completeText).toBeUndefined();
        },
    );
});

describe('publishableText', () => {
    it('prefers the formatter-composed whole response over re-joining the panes', () => {
        expect(
            publishableText({
                text: 'Summary\n\n---\n*Powered by CopilotKit AI*',
                details: 'Details',
                completeText: 'Summary\n\nDetails\n\n---\n*Powered by CopilotKit AI*',
            }),
        ).toBe('Summary\n\nDetails\n\n---\n*Powered by CopilotKit AI*');
    });

    // Discord stores its first part in `text` as well; publishing both would repeat it.
    it('publishes Discord continuations once, in order, ahead of text', () => {
        expect(
            publishableText({ text: 'One', parts: ['One', 'Two', 'Three'], truncated: true }),
        ).toBe('One\n\nTwo\n\nThree');
    });

    // A FormattedResponse built before `completeText` existed — a hand-rolled fixture,
    // or a value read back from an older run — must serialize exactly as it used to.
    it('falls back to the historical text-then-details join without completeText', () => {
        expect(publishableText({ text: 'Summary', details: 'Details' })).toBe('Summary\n\nDetails');
        expect(publishableText({ text: 'Summary' })).toBe('Summary');
        expect(publishableText({ text: 'Summary', parts: [] })).toBe('Summary');
    });
});
